Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,9 +18,6 @@ jobs:
       with:
         python-version: '3.9'
 
-    - name: Install dependencies
-      run: pip install -r Task10/requirements.txt
-
     - name: Test the application
       run: python -m unittest discover 
 
@@ -32,7 +29,7 @@ jobs:
     - name: Deploy to EC2
       run: |
         ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
-          cd /home/ubuntu/Task/Task10 || { echo "Directory not found"; exit 1; }
+          cd /home/ubuntu/Task10 || { echo "Directory not found"; exit 1; }
           git pull origin main || { echo "Failed to pull from git"; exit 1; }
           docker build -t flask-app . || { echo "Docker build failed"; exit 1; }
           docker stop flask-app-container || true
